# Generated by Django 3.0.7 on 2020-06-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperitivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default='2020-06-24T17:27:00+03:00'),
            preserve_default=False,
        ),
    ]
