version: "3.3"

services:
  database:
    container_name: cursoriosdeluz_database
    image: postgres:12.8
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=datariosdeluz
      - POSTGRES_USER=userriosdeluz
      - POSTGRES_DB=riosdeluz
    ports:
      - 5433:5432
